no-firework-damage: true
# composters, vases, etc
no-special-block-interaction: true
invulnerable-armourstand-on-spawn: true
invulnerable-painting-on-spawn: true
invulnerable-item-frame-on-spawn: true
no-chicken-from-egg: true
no-snow-and-ice-formation: true
parkour-no-fall-damage: true
no-item-frame-rotation: true
no-destroy-painting: true
no-armourstand-manipulation: true
no-silverfish-burrow: true

change-biome-settings:
  default: plains
  sand: desert
  grass_block: forest
  oak_log: forest
  spruce_log: forest
  jungle_log: forest
  birch_log: forest
  oak_leaves: forest
  spruce_leaves: forest
  jungle_leaves: forest
  birch_leaves: forest
  dirt: forest
  gravel: forest
  podzol: forest
  barrier: forest
  snow: snowy_slopes


