api-version: 1.21
name: ${project.name}
main: fun.kaituo.gameutils.GameUtils
version: ${project.version}
authors: [ YFshadaow, LeChocolatChaud ]
commands:
  join:
    description: Join a game
    default: true
  rejoin:
    description: Rejoin game
    default: true
  forcestop:
    description: Force stop a game
    default: op
    aliases: [ fs ]
  changebiome:
    description: Change biome
    default: op
    aliases: [ cb ]
  placestand:
    description: Place an armor stand in front of start buttons to prevent grief clicking
    default: op
    aliases: [ ps ]
  rotatable:
    description: set item frame rotatable
    usage: /rotatable <x> <y> <z> [true|false]
    default: op
    aliases: [ rt ]