api-version: 1.21.4
name: GameUtils
main: fun.kaituo.gameutils.GameUtils
version: ${project.version}
libraries:
  - io.github.classgraph:classgraph:4.8.179
authors: [ YFshadaow, LeChocolatChaud ]
permissions:
  gameutils.*:
    description: GameUtils admin permission
    default: op
    children:
      gameutils.command.*:
        description: Allow player to use all GameUtils commands
        default: op
        children:
          gameutils.command.join:
            description: Allow player to use /join
            default: true
            children:
              gameutils.command.join.others:
                description: Allow player to join other players to a game
                default: op
          gameutils.command.joinall:
            description: Allow player to use /joinall
            default: op
          gameutils.command.forcestop:
            description: Allow player to use /forcestop
            default: op
          gameutils.command.tpgame:
            description: Allow player to use /tpgame
            default: op
          gameutils.command.placestand:
            description: Allow player to use /placestand
            default: op
          gameutils.command.changebiome:
            description: Allow player to use /changebiome
            default: op
          gameutils.command.layout:
            description: Allow player to use /layout
            default: op
          gameutils.command.gameitem:
            description: Allow player to use /gameitem
            default: op
          gameutils.command.gameloc:
            description: Allow player to use /gameloc
            default: op
          gameutils.command.gameinv:
            description: Allow player to use /gameinv
            default: op
          gameutils.command.rotatable:
            description: Allow player to use /rotatable
            default: op
          gameutils.command.droppable:
            description: Allow player to use /droppable
            default: op
          gameutils.command.clickable:
            description: Allow player to use /clickable
            default: op
          gameutils.command.maphotbar:
            description: Allow player to use /maphotbar
            default: true
          gameutils.command.align:
            description: Allow player to use /align reload
            default: op

commands:
  join:
    description: Join a game
    usage: /join <game> [player]
    aliases: [ wan, jiaru, play ]
  joinall:
    description: Join all players to a game
    usage: /joinall <game>
  forcestop:
    description: Force stop a game
    usage: /forcestop [game]
    aliases: [ fs ]
  tpgame:
    description: Teleport to the game location
    usage: /tpgame <game>
    aliases: [ tpg ]
  changebiome:
    description: Change biome
    usage: /changebiome <biome>/auto <radius> <square/circular>
    aliases: [ cb ]
  placestand:
    description: Place an armor stand in front of start buttons to prevent grief clicking
    usage: /placestand
  layout:
    description: Show the layout of the games
    usage: /layout
    aliases: [ buju ]
  gameitem:
    description: Save the item in main hand to the config file of current game
    usage: /gameitem <save/get/remove> <key>
    aliases: [ gitem ]
  gameloc:
    description: Save the location to the config file of current game
    usage: /gameloc <save/tp/remove> <key> [block/player]
    aliases: [ gloc ]
  gameinv:
    description: Save the current inventory to the config file of current game
    usage: /gameinv <save/apply/remove> <key>
    aliases: [ ginv ]
  rotatable:
    description: Set the facing item frame to be rotatable / not rotatable
    usage: /rotatable [true/false]
    aliases: [ rt ]
  droppable:
    description: Set the current item in hand to be droppable / not droppable
    usage: /droppable [true/false]
  clickable:
    description: Set the current item in hand to be clickable / not clickable
    usage: /clickable [true/false]
  maphotbar:
    description: Set the hotbar mapping for the current player
    usage: /maphotbar <Mapping(eg. 012345678)/reset>
    aliases: [ mhb ]
  align:
    description: Align the current position to axis.
    usage: /align